# alpine
FROM colorcoding/compiling:ibas-gtf-alpine as builder

# 安装Bash
RUN apk add --no-cache bash bash-doc bash-completion \
    && rm -rf /var/cache/apk/ \
    && rm -rf /tmp/*.apk \
    && /bin/bash

# 获取脚本
RUN set -x \
    && cd ${CODE_HOME} \
    && git clone --depth 1 https://github.com/avacloud/ibas.scripts.git \
    && find ./ibas.scripts/ -name "*.sh" -exec chmod +x {} \;
