# ubuntu
FROM colorcoding/compiling:ibas-gtf-alpine as builder

# 维护者
LABEL maintainer="Niuren.Zhu <niuren.zhu@icloud.com>"

# 安装Bash
RUN apk update \
    && apk upgrade \
    && apk add --no-cache bash bash-doc bash-completion \
    && rm -rf /var/cache/apk/* \
    && /bin/bash

# 获取脚本
RUN set -x \
    && cd ${CODE_HOME} \
    && git clone --depth 1 https://github.com/avacloud/ibas.scripts.git \
    && find ./ibas.scripts/ -name "*.sh" -exec chmod +x {} \;
