# ubuntu
FROM colorcoding/developing:ibas as builder

# 维护者
LABEL maintainer="Niuren.Zhu <niuren.zhu@icloud.com>"

# 获取脚本
RUN set -x \
    && cd ${CODE_HOME} \
    && git clone --depth 1 https://github.com/avacloud/ibas.scripts.git \
    && find ./ibas.scripts/ -name "*.sh" -exec chmod +x {} \;
