# escape=`
# windows server core
FROM avacloud/tomcat:ibas-wincore

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

# 拷贝安装包
# 注意：需要包含安装包里的[Prerequisites]和[DI API]目录
ADD Packages C:\Packages

# 安装B1 DI API
RUN Start-Process -FilePath 'C:\Packages\DI API\setup.exe' -ArgumentList "/S","/v/qn" -Wait -NoNewWindow -PassThru; `
    IF ((Test-Path 'C:\Program Files\SAP\SAP Business One DI API') -ne 'True') { `
        Write-Host 'FAILED installing DI API!' ; exit 1; `
    }; `
    Remove-Item -Force -LiteralPath 'C:\Packages' -Recurse;

# 复制DI JCO到共享目录
RUN New-Item -Path 'C:/apache-tomcat/' -Name ibas_lib -Type Directory; `
    Copy-Item 'C:/Program Files/SAP/SAP Business One DI API/JCO/LIB/sboapi.jar' 'C:/apache-tomcat/ibas_lib/sboapi-latest.jar'; `
    Copy-Item 'C:/Program Files/SAP/SAP Business One DI API/JCO/LIB/sbowrapper.jar' 'C:/apache-tomcat/ibas_lib/sbowrapper-latest.jar';