# alpine
FROM colorcoding/compiling:ibas-alpine as builder

# 工具版本
ARG GIT_TF_VERSION=2.0.3.20131219
# 安装工具
RUN set -x \
    # 下载GIT-TF
    && curl -sL https://download.microsoft.com/download/A/E/2/AE23B059-5727-445B-91CC-15B7A078A7F4/git-tf-${GIT_TF_VERSION}.zip -O \
    # 解压安装
    && unzip -o git-tf-${GIT_TF_VERSION}.zip -d /usr/share/ \
    && ln -s /usr/share/git-tf-${GIT_TF_VERSION}/git-tf /usr/bin/git-tf \
    # 删除文件
    && rm -rf ./git-tf-${GIT_TF_VERSION}.zip
# 设置环境变量
ENV GITTF_HOME /usr/share/git-tf-${GIT_TF_VERSION}/

# 安装Bash
RUN apk add --no-cache bash bash-doc bash-completion \
    && rm -rf /var/cache/apk/ \
    && rm -rf /tmp/*.apk \
    && /bin/bash

