# alpine
FROM avacloud/tomcat:ibas-alpine

# 安装必须字体
RUN apk add --no-cache msttcorefonts-installer \
    && update-ms-fonts && fc-cache -f \
    && curl -sL http://nexus.avacloud.com.cn/repository/software/avatech/fonts/fake_simsun.ttc -O \
    && mv -f fake_simsun.ttc /usr/share/fonts/truetype/msttcorefonts/ \
    && ln -s /usr/share/fonts/truetype/msttcorefonts /opt/java/openjdk/jre/lib/fonts \
    && rm -rf /var/cache/apk/ \
    && rm -rf /tmp/*.apk 

# 安装水晶报表运行库
RUN set -x \
    && mkdir -p ${CATALINA_HOME}/webapps/crystalreports \
    && curl -sL http://nexus.avacloud.com.cn/repository/software/avatech/crystalreport/CR4ERL28_0-80004572.ZIP -O \
    && unzip -d ./crystalreport CR4ERL28_0-80004572.ZIP \
    && rm -rf CR4ERL28_0-80004572.ZIP \
    && cp -r ./crystalreport/crystalreportviewers ${CATALINA_HOME}/webapps/crystalreports/viewers \
    && cp -r ./crystalreport/lib ${CATALINA_HOME}/webapps/crystalreports/jars \
    && rm -rf ./crystalreport

# 恢复tomat的jsp检查
COPY conf/context.xml ${CATALINA_HOME}/conf/context.xml