# alpine
FROM avacloud/tomcat:ibas-alpine

# 安装nginx
RUN apk add --no-cache nginx \
    && rm -rf /var/cache/apk/ \
    && rm -rf /tmp/*.apk 

# 配置文件
COPY conf/nginx.conf /etc/nginx/nginx.conf
COPY conf/nginx_tomcat.conf /etc/nginx/conf.d/default.conf

RUN echo '#!/bin/sh' >/entrypoint.sh \
    && echo 'nohup nginx -g "daemon off;" &' >>/entrypoint.sh \
    && echo 'catalina.sh run' >>/entrypoint.sh \
    && chmod +x /entrypoint.sh

EXPOSE 80
ENTRYPOINT [ "/entrypoint.sh" ]