# escape=`
# windows server core
FROM colorcoding/tomcat:ibas-wincore

# 安装系统环境
# 请自行准备oledlg.dll
COPY oledlg_x64.dll C:\windows\System32\oledlg.dll
COPY oledlg_x86.dll C:\windows\SysWOW64\oledlg.dll
